# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "node-app-de-omar"
      PATH: "./node-app"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./node-app/
      # Uncomment to validate your work (should fail the next step)
      # - run: echo 'Hello Error' > ./index.js
      - run: docker container run --volume="${PATH}":"${PATH}" --workdir="${PATH}" "${IMAGE_NAME}" npm run lint