name: Docker Build and Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-unstable'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}-unstable" >> $GITHUB_OUTPUT
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cihaaan
          password: "${{ secrets.DOCKER_TOKEN }}"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: "cihaaan/esgi-ci-cd:${{ steps.get_version.outputs.VERSION }}"