# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  lint_docker:
    runs-on: hadolint/hadolint-action@v3.1.0
    with:
      dockerfile: ./node-app/Dockerfile


  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "node-app-de-omar"
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker image build --tag="${IMAGE_NAME}" ./node-app/
      - name: Run lint
        run: docker container run --volume="${GITHUB_WORKSPACE}/node-app":"${GITHUB_WORKSPACE}/node-app" "${IMAGE_NAME}" npm run lint