# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "cihaaan"
    steps:
      - uses: actions/checkout@v4
      - run: docker image build --tag="${IMAGE_NAME}/${IMAGE_VERSION}" ./
      - run: docker login -u cihaaan -p ${DOCKER_TOKEN}
      - run: docker image push "${IMAGE_NAME}/${IMAGE_VERSION}"