# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "node-app-de-omar"
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker image build --tag="${IMAGE_NAME}" ./node-app/
      - name: create file to lint
        run: echo "console.log('HELLOWORLD');" > index.js
      - name: Run lint
      #  --volume="${GITHUB_WORKSPACE}/node-app":"${GITHUB_WORKSPACE}/app" 
        run: docker container run --workdir="${GITHUB_WORKSPACE}/app" "${IMAGE_NAME}" npm run lint